console.log('butai son');

var searchType =[
	{ Id:1, Value:'Butai pardavimui' },
	{ Id:2, Value:'Namai pardavimui' },
	{ Id:3, Value:'Patalpos pardavimui' },
	{ Id:4, Value:'Butai nuomai' },
	{ Id:5, Value:'Namai nuomai' },
	{ Id:6, Value:'Patalpos nuomai' },
	{ Id:11, Value:'Sklypai' },
	{ Id:13, Value:'Garazai' },
	{ Id:9, Value:'Sodybos' },
	{ Id:12, Value:'Trumpalaike nuoma' },
	{ Id:10, Value:'Iesko NT' },
];

var regions = [
    { Id: 7361, Value: "Žvirgždės k." },
    { Id: 7387, Value: "Žiegždrių k." },
    { Id: 7416, Value: "Žemaitkiemio k." },
    { Id: 7360, Value: "Žėbiškių k." },
    { Id: 7197, Value: "Žėbiškėlių k." },
    { Id: 7288, Value: "Zizų k." },
    { Id: 7195, Value: "Zauniškių k." },
    { Id: 7287, Value: "Zapyškio mstl." },
    { Id: 7135, Value: "Zacišiaus k." },
    { Id: 7268, Value: "Voškonių k." },
    { Id: 7134, Value: "Vosiškių k." },
    { Id: 7267, Value: "Vytėnų k." },
    { Id: 7399, Value: "Viršužiglio k." },
    { Id: 7359, Value: "Virbaliūnų k." },
    { Id: 7324, Value: "Virbališkių k." },
    { Id: 7378, Value: "Vingytės k." },
    { Id: 7286, Value: "Vincentavo k." },
    { Id: 7148, Value: "Vimbarų k." },
    { Id: 7194, Value: "Vilkijos k." },
    { Id: 7132, Value: "Vilkėnų k." },
    { Id: 7285, Value: "Vilemų k." },
    { Id: 7133, Value: "Vikūnų k." },
    { Id: 7415, Value: "Vijūkų k." },
    { Id: 7147, Value: "Vigių k." },
    { Id: 7400, Value: "Vyčiaus k." },
    { Id: 7266, Value: "Varluvos k." },
    { Id: 7131, Value: "Vareikonių k." },
    { Id: 7146, Value: "Vandžiogalos mstl." },
    { Id: 7193, Value: "Valmantiškių k." },
    { Id: 7265, Value: "Valeravos k." },
    { Id: 7192, Value: "Vaitkūnų k." },
    { Id: 7386, Value: "Vaišvydavos k." },
    { Id: 7304, Value: "Vaistariškių k." },
    { Id: 7398, Value: "Vainatrakio k." },
    { Id: 7397, Value: "Užupių k." },
    { Id: 7145, Value: "Užumiškių k." },
    { Id: 7414, Value: "Užliedžių k." },
    { Id: 7447, Value: "Uždulinskių k." },
    { Id: 7130, Value: "Urnėžių k." },
    { Id: 7358, Value: "Upytės k." },
    { Id: 7223, Value: "Tvarkiškių k." },
    { Id: 7396, Value: "Tursono k." },
    { Id: 7096, Value: "Tumpų k." },
    { Id: 7357, Value: "Tolivardžių k." },
    { Id: 7356, Value: "Tirkšlių k." },
    { Id: 7095, Value: "Tirkiliškių k." },
    { Id: 7222, Value: "Teleičių k." },
    { Id: 7446, Value: "Teklinavos k." },
    { Id: 7264, Value: "Tauralaukio k." },
    { Id: 7395, Value: "Taurakiemio k." },
    { Id: 7323, Value: "Tabariškių k." },
    { Id: 7191, Value: "Šolių k." },
    { Id: 7094, Value: "Šniūrų k." },
    { Id: 7385, Value: "Šlienavos k." },
    { Id: 7284, Value: "Šiulių k." },
    { Id: 7093, Value: "Šilėnų k." },
    { Id: 7355, Value: "Šilelio k." },
    { Id: 7263, Value: "Šatijų k." },
    { Id: 7129, Value: "Šašių k." },
    { Id: 7262, Value: "Šančių k." },
    { Id: 7261, Value: "Šakių k." },
    { Id: 7260, Value: "Staviščių k." },
    { Id: 7259, Value: "Stavidvario k." },
    { Id: 7258, Value: "Stankūnų k." },
    { Id: 7190, Value: "Stanislavos k." },
    { Id: 7221, Value: "Stanaičių k." },
    { Id: 7128, Value: "Stabaunyčiaus k." },
    { Id: 7220, Value: "Sprindiškių k." },
    { Id: 7257, Value: "Smiltynų II k." },
    { Id: 7256, Value: "Smiltynų I k." },
    { Id: 7091, Value: "Smailių k." },
    { Id: 7255, Value: "Skrebiniškių k." },
    { Id: 7189, Value: "Skrebenų k." },
    { Id: 7127, Value: "Sitkūnų k." },
    { Id: 7394, Value: "Sietyno k." },
    { Id: 7445, Value: "Severinavos k." },
    { Id: 7303, Value: "Sergeičikų II k." },
    { Id: 7302, Value: "Sergeičikų I k." },
    { Id: 7354, Value: "Senųjų Bernatonių k." },
    { Id: 7219, Value: "Seniavos k." },
    { Id: 7126, Value: "Selveravos k." },
    { Id: 7412, Value: "Sausinės k." },
    { Id: 7188, Value: "Saulėtekių k." },
    { Id: 7384, Value: "Samylų k." },
    { Id: 7253, Value: "Salių k." },
    { Id: 7322, Value: "Sakalų k." },
    { Id: 7353, Value: "Rupunionių k." },
    { Id: 7283, Value: "Rupinų k." },
    { Id: 7352, Value: "Ručkūnų k." },
    { Id: 7187, Value: "Ručkonių k." },
    { Id: 7250, Value: "Romaškių k." },
    { Id: 7411, Value: "Romainių Kaimelės k." },
    { Id: 7410, Value: "Romainių k." },
    { Id: 7375, Value: "Rokų Miško Kelmyno k." },
    { Id: 7374, Value: "Rokų k." },
    { Id: 7252, Value: "Rokiškių k." },
    { Id: 7144, Value: "Rokiškio k." },
    { Id: 7373, Value: "Rokelių k." },
    { Id: 7282, Value: "Riogliškių k." },
    { Id: 7218, Value: "Rinkūnų k." },
    { Id: 7186, Value: "Ringovės k." },
    { Id: 7321, Value: "Ringaudų k." },
    { Id: 7301, Value: "Rykštynės k." },
    { Id: 7251, Value: "Ražių k." },
    { Id: 7217, Value: "Ražiškių k." },
    { Id: 7372, Value: "Raželių k." },
    { Id: 7444, Value: "Raudonės k." },
    { Id: 7351, Value: "Raudondvario k." },
    { Id: 7185, Value: "Raubatonių k." },
    { Id: 7216, Value: "Rašnavos k." },
    { Id: 7300, Value: "Ramučių k." },
    { Id: 7443, Value: "Ramonų k." },
    { Id: 24188, Value: "Raguolių k." },
    { Id: 7442, Value: "Radviliškių k." },
    { Id: 7249, Value: "Radikių k." },
    { Id: 7184, Value: "Purviškių k." },
    { Id: 7441, Value: "Purvaičių k." },
    { Id: 7248, Value: "Puikonių k." },
    { Id: 7440, Value: "Prienų k." },
    { Id: 7247, Value: "Preišiogalos k." },
    { Id: 7320, Value: "Poderiškių k." },
    { Id: 7143, Value: "Pociūnų k." },
    { Id: 7319, Value: "Pyplių k." },
    { Id: 7393, Value: "Piliuonos k." },
    { Id: 7125, Value: "Piepalių k." },
    { Id: 7299, Value: "Pelenių k." },
    { Id: 7089, Value: "Pažėrų k." },
    { Id: 7370, Value: "Pavytės k." },
    { Id: 7124, Value: "Pavejuonio k." },
    { Id: 7369, Value: "Patamulšėlio k." },
    { Id: 7350, Value: "Paštuvos k." },
    { Id: 7183, Value: "Pašilių k." },
    { Id: 7182, Value: "Pastriūnio k." },
    { Id: 7181, Value: "Partikų k." },
    { Id: 7368, Value: "Paraželių k." },
    { Id: 7180, Value: "Paprūdžių k." },
    { Id: 7439, Value: "Paprienių k." },
    { Id: 7281, Value: "Papiškių k." },
    { Id: 7409, Value: "Paparčių k." },
    { Id: 7122, Value: "Panevėžiuko k." },
    { Id: 7367, Value: "Pamoterio k." },
    { Id: 7088, Value: "Pamaišupio k." },
    { Id: 7408, Value: "Paltiškių k." },
    { Id: 7179, Value: "Palazduonio k." },
    { Id: 7121, Value: "Pakapių k." },
    { Id: 7246, Value: "Pakalniškių k." },
    { Id: 7215, Value: "Pajiesio k." },
    { Id: 7438, Value: "Pagirių k." },
    { Id: 7120, Value: "Pagynės k." },
    { Id: 7437, Value: "Padubysio k." },
    { Id: 7177, Value: "Padauguvos k." },
    { Id: 7176, Value: "Padauguvėlės k." },
    { Id: 7245, Value: "Padaugupio k." },
    { Id: 7087, Value: "Padainupio k." },
    { Id: 7298, Value: "Pabiržio k." },
    { Id: 7086, Value: "Pabartupio k." },
    { Id: 7175, Value: "Pabalių k." },
    { Id: 7280, Value: "Novos k." },
    { Id: 7318, Value: "Noreikiškių k." },
    { Id: 7297, Value: "Neveronių k." },
    { Id: 7349, Value: "Netonių k." },
    { Id: 7117, Value: "Naujųjų Muniškių k." },
    { Id: 7348, Value: "Naujųjų Bernatonių k." },
    { Id: 7347, Value: "Naujienos k." },
    { Id: 7346, Value: "Naujatriobių k." },
    { Id: 7118, Value: "Naujasodžių k." },
    { Id: 7296, Value: "Naujasodžio k." },
    { Id: 7213, Value: "Naugardiškės k." },
    { Id: 7084, Value: "Narsiečių k." },
    { Id: 7295, Value: "Narėpų k." },
    { Id: 7407, Value: "Muniškių k." },
    { Id: 7345, Value: "Mozūriškių k." },
    { Id: 7316, Value: "Mitkūnų k." },
    { Id: 7344, Value: "Miškinių k." },
    { Id: 7436, Value: "Miškalaukio k." },
    { Id: 7317, Value: "Miriniškių k." },
    { Id: 7435, Value: "Mikniavos k." },
    { Id: 7434, Value: "Mikliūnų k." },
    { Id: 7141, Value: "Mėklos k." },
    { Id: 7244, Value: "Mažųjų Ibėnų k." },
    { Id: 7243, Value: "Masteikių k." },
    { Id: 7083, Value: "Mastaičių k." },
    { Id: 7294, Value: "Martinavos k." },
    { Id: 7392, Value: "Margininkų k." },
    { Id: 7293, Value: "Margavos k." },
    { Id: 7343, Value: "Maksvos k." },
    { Id: 7082, Value: "Macijauskų k." },
    { Id: 7314, Value: "Luobinės k." },
    { Id: 7342, Value: "Lukšakaimio k." },
    { Id: 7341, Value: "Lomankos k." },
    { Id: 7433, Value: "Liučiūnų k." },
    { Id: 7432, Value: "Lipikiškių k." },
    { Id: 7405, Value: "Linkuvos k." },
    { Id: 7212, Value: "Linksmakalnio k." },
    { Id: 7174, Value: "Lygainių k." },
    { Id: 7173, Value: "Liepdvario k." },
    { Id: 7242, Value: "Lepšiškių k." },
    { Id: 7391, Value: "Leonavo k." },
    { Id: 7431, Value: "Lelerviškių k." },
    { Id: 7430, Value: "Lebedžių k." },
    { Id: 7172, Value: "Lazduonių k." },
    { Id: 7116, Value: "Lazdynės k." },
    { Id: 7383, Value: "Laumėnų k." },
    { Id: 7171, Value: "Lauksvydų k." },
    { Id: 7241, Value: "Lapių mstl." },
    { Id: 7340, Value: "Kvesų k." },
    { Id: 7279, Value: "Kuro k." },
    { Id: 7313, Value: "Kuodiškių k." },
    { Id: 7240, Value: "Kumpių k." },
    { Id: 44, Value: "Kulautuvos mstl." },
    { Id: 7081, Value: "Kūjagalvių k." },
    { Id: 7404, Value: "Kudrėnų k." },
    { Id: 7170, Value: "Krūvandų k." },
    { Id: 7277, Value: "Krušinskų k." },
    { Id: 7115, Value: "Krivėnų k." },
    { Id: 7339, Value: "Kriemalos k." },
    { Id: 7276, Value: "Kluoniškių k." },
    { Id: 7429, Value: "Kilovos k." },
    { Id: 7114, Value: "Kikonių k." },
    { Id: 7239, Value: "Kėkštynės k." },
    { Id: 7312, Value: "Kazliškių k." },
    { Id: 7238, Value: "Kazimieravos k." },
    { Id: 7292, Value: "Kaukazo k." },
    { Id: 7338, Value: "Karnavės k." },
    { Id: 7290, Value: "Karmėlavos II k." },
    { Id: 7291, Value: "Karmėlavos mstl." },
    { Id: 7311, Value: "Karkiškių k." },
    { Id: 7211, Value: "Karkazų k." },
    { Id: 7140, Value: "Karaliūnų k." },
    { Id: 7428, Value: "Karalgirio k." },
    { Id: 7112, Value: "Kaniūkų k." },
    { Id: 7080, Value: "Kampiškių k." },
    { Id: 7337, Value: "Kalnyčių k." },
    { Id: 7210, Value: "Kalinavos k." },
    { Id: 7365, Value: "Kairiūkščių k." },
    { Id: 7427, Value: "Kairių k." },
    { Id: 7336, Value: "Kačiūniškės k." },
    { Id: 7111, Value: "Kačergių k." },
    { Id: 43, Value: "Kačerginės mstl." },
    { Id: 7426, Value: "Juškaičių k." },
    { Id: 7207, Value: "Jurginiškių k." },
    { Id: 7208, Value: "Juraitiškės k." },
    { Id: 7206, Value: "Juragių k." },
    { Id: 7139, Value: "Juozapavos k." },
    { Id: 7168, Value: "Juodžių k." },
    { Id: 7110, Value: "Juodonių k." },
    { Id: 7109, Value: "Jugintų k." },
    { Id: 7275, Value: "Judraičių k." },
    { Id: 7167, Value: "Jotautų k." },
    { Id: 7205, Value: "Jonučių II k." },
    { Id: 7079, Value: "Jonučių k." },
    { Id: 7166, Value: "Jokavų k." },
    { Id: 7165, Value: "Jaučakių k." },
    { Id: 7108, Value: "Janušonių k." },
    { Id: 7164, Value: "Jagminiškių k." },
    { Id: 7274, Value: "Jadagonių k." },
    { Id: 7237, Value: "Jackiškių k." },
    { Id: 7204, Value: "Ireniškių k." },
    { Id: 7203, Value: "Ilgakiemio k." },
    { Id: 7390, Value: "Guogų k." },
    { Id: 7163, Value: "Gudravio k." },
    { Id: 7202, Value: "Grabavos k." },
    { Id: 7335, Value: "Godėnų k." },
    { Id: 7382, Value: "Girionių k." },
    { Id: 7310, Value: "Girininkų II k." },
    { Id: 7077, Value: "Girininkų I k." },
    { Id: 7364, Value: "Girininkų k." },
    { Id: 7403, Value: "Giraitės k." },
    { Id: 7236, Value: "Ginėnų k." },
    { Id: 7331, Value: "Gineitų k." },
    { Id: 7162, Value: "Gineikių k." },
    { Id: 7381, Value: "Gervėnupio k." },
    { Id: 7235, Value: "Geranonių k." },
    { Id: 7425, Value: "Gegužėnų k." },
    { Id: 7200, Value: "Garančiškės k." },
    { Id: 7138, Value: "Galulaukės k." },
    { Id: 7107, Value: "Gaižuvėlės k." },
    { Id: 7309, Value: "Gaižėnų k." },
    { Id: 7308, Value: "Gaižėnėlių k." },
    { Id: 7106, Value: "Gailiušių k." },
    { Id: 7160, Value: "Gailiūnų k." },
    { Id: 7424, Value: "Gaigalų k." },
    { Id: 7159, Value: "Gaideliškių k." },
    { Id: 7423, Value: "Eikščių k." },
    { Id: 7234, Value: "Eigirgalos k." },
    { Id: 7105, Value: "Eglynų k." },
    { Id: 7273, Value: "Durpyno k." },
    { Id: 7334, Value: "Dūmino k." },
    { Id: 7333, Value: "Dulkių k." },
    { Id: 7380, Value: "Dubravų k." },
    { Id: 7233, Value: "Drąseikių k." },
    { Id: 7232, Value: "Domeikavos k." },
    { Id: 7422, Value: "Dokių k." },
    { Id: 7421, Value: "Dokelių k." },
    { Id: 7389, Value: "Dobilijos k." },
    { Id: 7076, Value: "Digrių k." },
    { Id: 7272, Value: "Dievogalos k." },
    { Id: 7231, Value: "Didžiųjų Lapių k." },
    { Id: 7230, Value: "Didžiųjų Ibėnų k." },
    { Id: 7332, Value: "Didvyrių k." },
    { Id: 7158, Value: "Daugužių k." },
    { Id: 7157, Value: "Daugeliškių k." },
    { Id: 7156, Value: "Daučionių k." },
    { Id: 7104, Value: "Dasiūnų k." },
    { Id: 7363, Value: "Dankstytės k." },
    { Id: 7420, Value: "Čekiškės mstl." },
    { Id: 7307, Value: "Čebeliškės k." },
    { Id: 7103, Value: "Cinkiškių k." },
    { Id: 7137, Value: "Butkūnų k." },
    { Id: 7155, Value: "Buivydų k." },
    { Id: 7199, Value: "Budrių k." },
    { Id: 7330, Value: "Bubių k." },
    { Id: 7329, Value: "Brūžės k." },
    { Id: 7271, Value: "Braziūkų k." },
    { Id: 7229, Value: "Boniškių k." },
    { Id: 7073, Value: "Bliovų k." },
    { Id: 7402, Value: "Bivylių k." },
    { Id: 7228, Value: "Bitvano k." },
    { Id: 7289, Value: "Biruliškių k." },
    { Id: 7328, Value: "Biliūnų k." },
    { Id: 7072, Value: "Bijūnų k." },
    { Id: 7419, Value: "Besmerčių k." },
    { Id: 7154, Value: "Bernoriškių k." },
    { Id: 7327, Value: "Bernatonių k." },
    { Id: 7102, Value: "Berlainių k." },
    { Id: 7326, Value: "Beiniūnų k." },
    { Id: 7325, Value: "Batniavos k." },
    { Id: 7227, Value: "Barsūniškių k." },
    { Id: 7153, Value: "Baravų k." },
    { Id: 7101, Value: "Baltriškės k." },
    { Id: 7306, Value: "Bajorų k." },
    { Id: 7198, Value: "Bagniškės k." },
    { Id: 7099, Value: "Babtų k." },
    { Id: 7100, Value: "Babtų mstl." },
    { Id: 7226, Value: "Ąžuolyno k." },
    { Id: 7152, Value: "Aukštkalnių k." },
    { Id: 7225, Value: "Audėjų k." },
    { Id: 7305, Value: "Armaniškių k." },
    { Id: 7388, Value: "Arlaviškių k." },
    { Id: 7418, Value: "Antkalnių k." },
    { Id: 7151, Value: "Antalkių k." },
    { Id: 7098, Value: "Antagynės k." },
    { Id: 7097, Value: "Antagynėlių k." },
    { Id: 7224, Value: "Andruškonių k." },
    { Id: 7270, Value: "Altoniškių k." },
    { Id: 7070, Value: "Alšėnų k." },
    { Id: 7150, Value: "Akuotų k." },
    { Id: 7315, Value: "Akademijos mstl." },
    { Id: 7149, Value: "Adomkiškių k." },
    { Id: 41, Value: "Vilkijos m." },
    { Id: 42, Value: "Garliavos m." },
    { Id: 45, Value: "Ežerėlio m." },
    { Id: "", Value: "Gyvenvietė" },
    { Id: 99999, Value: "Visa Lietuva" },
    { Id: "--", Value: "------------------------" },
    { Id: 403, Value: "Zarasų r." },
    { Id: 459, Value: "Visagino sav." },
    { Id: 462, Value: "Vilniaus r." },
    { Id: 163, Value: "Vilkaviškio r." },
    { Id: 16, Value: "Varėnos r." },
    { Id: 449, Value: "Utenos r." },
    { Id: 501, Value: "Ukmergės r." },
    { Id: 487, Value: "Trakų r." },
    { Id: 381, Value: "Telšių r." },
    { Id: 323, Value: "Tauragės r." },
    { Id: 526, Value: "Švenčionių r." },
    { Id: 539, Value: "Širvintų r." },
    { Id: 146, Value: "Šilutės r." },
    { Id: 332, Value: "Šilalės r." },
    { Id: 311, Value: "Šiaulių r." },
    { Id: 513, Value: "Šalčininkų r." },
    { Id: 187, Value: "Šakių r." },
    { Id: 136, Value: "Skuodo r." },
    { Id: 438, Value: "Rokiškio r." },
    { Id: 1197, Value: "Rietavo sav." },
    { Id: 98, Value: "Raseinių r." },
    { Id: 298, Value: "Radviliškio r." },
    { Id: 86, Value: "Prienų r." },
    { Id: 367, Value: "Plungės r." },
    { Id: 247, Value: "Pasvalio r." },
    { Id: 235, Value: "Panevėžio r." },
    { Id: 289, Value: "Pakruojo r." },
    { Id: 1196, Value: "Pagėgių sav." },
    { Id: 113, Value: "Neringos sav." },
    { Id: 426, Value: "Molėtų r." },
    { Id: 359, Value: "Mažeikių r." },
    { Id: 162, Value: "Marijampolės sav." },
    { Id: 27, Value: "Lazdijų r." },
    { Id: 228, Value: "Kupiškio r." },
    { Id: 127, Value: "Kretingos r." },
    { Id: 115, Value: "Klaipėdos r." },
    { Id: 278, Value: "Kelmės r." },
    { Id: 215, Value: "Kėdainių r." },
    { Id: 1193, Value: "Kazlų Rūdos sav." },
    { Id: 63, Value: "Kauno r." },
    { Id: 1192, Value: "Kalvarijos sav." },
    { Id: 53, Value: "Kaišiadorių r." },
    { Id: 346, Value: "Jurbarko r." },
    { Id: 267, Value: "Joniškio r." },
    { Id: 44, Value: "Jonavos r." },
    { Id: 413, Value: "Ignalinos r." },
    { Id: 1191, Value: "Elektrėnų sav." },
    { Id: 3, Value: "Druskininkų sav." },
    { Id: 206, Value: "Biržų r." },
    { Id: 42, Value: "Birštono sav." },
    { Id: 393, Value: "Anykščių r." },
    { Id: 4, Value: "Alytaus r." },
    { Id: 260, Value: "Akmenės r." },
    { Id: "-", Value: "" },
    { Id: 114, Value: "Palanga" },
    { Id: 2, Value: "Alytus" },
    { Id: 205, Value: "Panevėžys" },
    { Id: 259, Value: "Šiauliai" },
    { Id: 112, Value: "Klaipėda" },
    { Id: 43, Value: "Kaunas" },
    { Id: 461, Value: "Vilnius" },
    { Id: 0, Value: "Savivaldybė" },
    { Id: 10, Value: "Ieško NT" },
    { Id: 12, Value: "Trumpalaikė nuoma" },
    { Id: 9, Value: "Sodybos" },
    { Id: 13, Value: "Garažai" },
    { Id: 11, Value: "Sklypai" },
    { Id: 6, Value: "Patalpos nuomai" },
    { Id: 5, Value: "Namai nuomai" },
    { Id: 4, Value: "Butai nuomai" },
    { Id: 3, Value: "Patalpos pardavimui" },
    { Id: 2, Value: "Namai pardavimui" },
    { Id: 1, Value: "Butai pardavimui" }
]

var searchOptions = {
	Plotas: {Nuo:null, Iki:null},
	Kambariai: {Nuo:null, Iki:null},
	Aukstas: {Nuo:null, Iki:null},
	AukstoTipas: null,
	Kaina: {Nuo:null, Iki:null}
};

var otherProperties = [
    { Id: "AreaOverall", alue: "Mažesni viršuje" }, 
    { Id: "PriceExp", alue: "Brangesni viršuje" }, 
    { Id: "Price", alue: "Pigesni viršuje" }, 
    { Id: "Actuality", alue: "Naujesni viršuje" }, 
    { Id: "Importance", alue: "Svarbesni viršuje" }, 
    { Id: 60, alue: "Dviejų mėnesių" }, 
    { Id: 30, alue: "Mėnesio" }, 
    { Id: 14, alue: "Dviejų savaičių" }, 
    { Id: 7, alue: "Savaitės" }, 
    { Id: 3, alue: "3 dienų" }, 
    { Id: 1, alue: "1 dienos" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: "Price", alue: "Pigesni viršuje" }, 
    { Id: "Actuality", alue: "Naujesni viršuje" }, 
    { Id: "Importance", alue: "Svarbesni viršuje" }, 
    { Id: "AreaOverall", alue: "Mažesni viršuje" }, 
    { Id: "Price", alue: "Pigesni viršuje" }, 
    { Id: "Actuality", alue: "Naujesni viršuje" }, 
    { Id: "Importance", alue: "Svarbesni viršuje" }, 
    { Id: 1, alue: "" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: 1, alue: "" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: 1, alue: "" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: "none", alue: "Kita" }, 
    { Id: "timber", alue: "Rąstinis" }, 
    { Id: "carcas", alue: "Karkasinis" }, 
    { Id: "wood", alue: "Medinis" }, 
    { Id: "monolith", alue: "Monolitinis" }, 
    { Id: "block", alue: "Blokinis" }, 
    { Id: "brick", alue: "Mūrinis" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: "none", alue: "Kita" }, 
    { Id: "foundation", alue: "Pamatai" }, 
    { Id: "n_finished", alue: "Nebaigtas statyti" }, 
    { Id: "noteq", alue: "Neįrengtas" }, 
    { Id: "part", alue: "Dalinė apdaila" }, 
    { Id: "full", alue: "Įrengtas" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: "none", alue: "Kita" }, 
    { Id: "n_finished", alue: "Nebaigtas statyti" }, 
    { Id: "noteq", alue: "Neįrengtas" }, 
    { Id: "part", alue: "Dalinė apdaila" }, 
    { Id: "full", alue: "Įrengtas" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: "none", alue: "Kita" }, 
    { Id: "timber", alue: "Rąstinis" }, 
    { Id: "carcas", alue: "Karkasinis" }, 
    { Id: "wood", alue: "Medinis" }, 
    { Id: "monolith", alue: "Monolitinis" }, 
    { Id: "block", alue: "Blokinis" }, 
    { Id: "brick", alue: "Mūrinis" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: 1, alue: "" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: 10, alue: "Garažai" }, 
    { Id: 9, alue: "Sodybos, sodai" }, 
    { Id: 8, alue: "Sklypai kaime" }, 
    { Id: 7, alue: "Sklypai mieste" }, 
    { Id: 6, alue: "Patalpos nuomai" }, 
    { Id: 5, alue: "Namai nuomai" }, 
    { Id: 4, alue: "Butai nuomai" }, 
    { Id: 3, alue: "Patalpos pardavimui" }, 
    { Id: 2, alue: "Namai pardavimui" }, 
    { Id: 1, alue: "Butai pardavimui" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: 9, alue: "Kita" }, 
    { Id: 4, alue: "Daugiaaukštis" }, 
    { Id: 3, alue: "Požeminis" }, 
    { Id: 2, alue: "Geležinis" }, 
    { Id: 1, alue: "Mūrinis" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: 2, alue: "Nuomai" }, 
    { Id: 1, alue: "Pardavimui" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: 2, alue: "Nuomai" }, 
    { Id: 1, alue: "Pardavimui" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: 5, alue: "Paskutinis" }, 
    { Id: 4, alue: "Pirmas" }, 
    { Id: 3, alue: "Ne pirm. ir ne pask." }, 
    { Id: 2, alue: "Ne paskutinis" }, 
    { Id: 1, alue: "Ne pirmas" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: 4, alue: "Pokylių salės" }, 
    { Id: 3, alue: "Sodybos" }, 
    { Id: 2, alue: "Kambariai" }, 
    { Id: 1, alue: "Butai" }, 
    { Id: 0, alue: "Pasirinkite" }, 
    { Id: "summerhouse", alue: "Sodyba" }, 
    { Id: "blocked", alue: "Sublokuotas namas" }, 
    { Id: "garden_house", alue: "Sodo namas" }, 
    { Id: "house_part", alue: "Namo dalis" }, 
    { Id: "box", alue: "Namas (gyvenamasis)" }, 
    { Id: 0, alue: "Pasirinkite"}
]

// 'http://www.aruodas.lt/namai/kauno-rajone/?detailed_search=&redirect_skelbiu=0&redirect_edomus=0&obj=2&FRegion=63&FDistrict=0&FBuildingType=house_part&FAreaOverAllMax=&FAreaOverAllMin=&FAreaLotMax=&FAreaLotMin=&FPriceMax=&FPriceMin='

// var items = []
// $('select.input-wide option');
// var Things = $('div.filter-col-1 select option');
// for (var i = Things.length - 1; i >= 0; i--) {
// 	var item = {};
// 	item.Id =	$(Things[i]).val();
// 	item.Value = $(Things[i]).html().trim();
// 	items.push(item);
// };

/* replaces
"Id": "([0-9]{1,6})"
Id: $1

"Value":
Value:

,
        V
, 

"
    },
" }, 

"Id":
Id:
*/


function processShit(htmlResponse){
    if(htmlResponse){
        console.log('Response: found');        
        console.log(htmlResponse.toString());
    }else{
        console.log('Response: empty');
    }
console.log('Response: END');
};

var url = 'http://www.aruodas.lt/namai/kauno-rajone/?detailed_search=&redirect_skelbiu=0&redirect_edomus=0&obj=2&FRegion=63&FDistrict=0&FBuildingType=house_part&FAreaOverAllMax=&FAreaOverAllMin=&FAreaLotMax=&FAreaLotMin=&FPriceMax=&FPriceMin=';

//httpGetAsync(url,processShit);

var sys = require('util');
var jquery = require('jquery');
var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

var xhr = new XMLHttpRequest();

xhr.onreadystatechange = function() {
    // console.log("State: " + this.readyState);
    
    if (this.readyState === 4) {
        if(this.responseText){
            console.log('Response: Success');
            var response = this.responseText;
            jsdom.env(
              this.responseText,
              ["http://code.jquery.com/jquery.js"],
              function (err, window) {
                console.log(window.$("div").length);
              }
            );
        }
    }


};

xhr.open("GET", url);
xhr.send();

var jsdom = require("jsdom");
 
